### ISSUE TITLE
RMQ

### ISSUE THREAD

**Issue by mzuenni** [pjungeblut/ChaosKITs#27]
It is possible to implement RMQ to answere queries in constant time and still only need linear space. How big would the improvement of that algorithm be for icpc purpose?

**Comment by pjungeblut** [comment]
It is possible (O(n) space + O(n) precalc + O(1) queries), but I think this is an overkill. All approaches I know of definitely are. If you find one with short and easy code I will happily take it into the TCR.

Anyway, in ICPC, logarithms barely matter. There is only a very few tasks, where they make a difference. Keep in mind, that log2(10^6) ~ 20, so a bad implementation has the same effect.
