### ISSUE TITLE
Bit Operations

### ISSUE THREAD

**Issue by pjungeblut** [pjungeblut/ChaosKITs#32]
https://pastebin.com/1WDGcF6P

**Comment by mzuenni** [comment]
kann man die builtins benutzten?
int __builtin_popcount (unsigned int x);
int __builtin_popcountll (unsigned long long x);

und hier sind noch ein paar ganz tolle wege dafür:
https://graphics.stanford.edu/~seander/bithacks.html

**Comment by pjungeblut** [comment]
Dafür müsste man wissen, ob die auf den Contestmaschinen unterstützt werden. Vermutlich ja
